### ISSUE TITLE
suggestion to eliminate the need of the BE doing a tx to set the viewing key

### ISSUE THREAD

**Issue by baedrik** [kevinakidd/SNIP-721-Proof-of-Ownership-Discord-Bot#1]
Great job!  Just thought I'd leave a suggestion in case you have time to explore it.

Since a permit is just a JSON string (where the object fields are in a mandatory order), the secp256k1 public key, and the secp256k1 signature of that JSON signed by the secp256k1 private key corresponding to the public key in the permit, you can actually create a permit without needing keplr.  So you could avoid the need for the BE to do a tx to create a viewing key.

Besides eliminating the need for gas, that also means that if you wanted to make it usable for any number of collections, you can just either create new, individual permits, or just create a new single permit that is good for all the collections without needing to set a key with every one.

**Comment by kevin-kidd** [comment]
Thank you for the advice!

I will change to using permits for the BE. As per your advisement, I will add a disclaimer for pre-shockwave collections with regards to their resource consumption using permits.
